### PR TITLE
changed the footer descrption

### PR DESCRIPTION
**Pull request by jaseempaloth**

### CODE REVIEW

**Comment by jaseempaloth** [comment]
hi

**Comment by aneebp** [comment]
Hyyy

**Comment by aneebp** [comment]
hhh

**Comment by jaseempaloth** [comment]
fixed the image

**Comment by jaseempaloth** [comment]
fixed image

**Review by aneebp — COMMENTED** [review]
good

**Comment by aneebp** [comment]
well done

**Pull request closed without merging**
